feat(dropbox): upload file action
RolloutHQ/rollout pull request #3
Opened 2024-04-04 17:36 UTC by mike-rollout

2024-04-05 00:15 UTC, blaise-bradley requested changes

2024-04-05 00:15 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +  const originalExtension = originalFilename.includes(".")
Consider using `path.extension`. See `google-drive` `upload-file` action as a reference.

2024-04-05 00:15 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +    const request = https.get(url, (response) => {
Would prefer using `undici.fetch` like we do in `google-drive` `upload-file`, since we typically work with promises rather than callbacks. 

Also, wondering if it's worth creating a shared util for "fetch file from url", since we're likely doing the same thing in both places?

2024-04-05 00:15 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/actions/upload-file/ui.tsx
> +          { id: "no", name: "No" },
Would like to standardize on `"true"` and `"false"` for dropdowns representing fields that are represent boolean values. See this issue: https://github.com/RolloutHQ/rollout/issues/8

2024-04-05 00:15 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/lib/ui/dropbox-chooser.tsx
> +import loadScript from "load-script";
@dodas Could you please take a look at the UI changes here?

2024-04-05 00:15 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/queries.ts
> +import { Dropbox, DropboxResponse, files } from "dropbox";
Is this file used? Looks like these queries are for allowing the user to select the folder to upload too, but we're now using the native Dropbox file picker.

2024-04-09 16:46 UTC, dodas commented on packages/connectors/src/apps/dropbox/lib/ui/folder-picker.tsx
> +              cancel={() => console.log("closed")}
```suggestion
```

2024-04-11 20:45 UTC, dodas commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +    const { result, status } = await dropbox.filesUpload(uploadArgs);
would prefer to just put this inline, something like this:
```suggestion
    const { result, status } = await dropbox.filesUpload({
      path: dropboxPath,
      contents: readable,
      mode: overwrite === "true" ? { ".tag": "overwrite" } : undefined
    });
```

2024-04-11 20:53 UTC, dodas commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +    const contentLength = headers.get("content-length") ?? null;
hmm, the `content-length` header will not always be available. I am wondering what will happen if we don't check here and just stream more data do dropbox – will it throw an error that we can potentially catch and interpret?

2024-04-11 21:04 UTC, dodas commented on packages/connectors/src/apps/dropbox/lib/ui/folder-picker.tsx
> +export default FolderPicker;
please export it where declared (`export function FolderPicker`)

2024-04-11 21:05 UTC, dodas commented on packages/connectors/src/apps/dropbox/oauth.ts
> +export const oauth = defineRolloutOAuth2Service<DropboxCredential>()({
please merge latest `main` and refactor `auth` (`oauth` callbacks are now defined in `auth.ts`)

2024-04-12 14:16 UTC, mike-rollout commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +    const contentLength = headers.get("content-length") ?? null;
We are checking this in line 56

2024-04-12 14:32 UTC, mike-rollout commented on packages/connectors/src/apps/dropbox/actions/upload-file/action.ts
> +    const contentLength = headers.get("content-length") ?? null;
Let me check if that is possible

2024-04-15 14:34 UTC, blaise-bradley requested changes

2024-04-15 14:34 UTC, blaise-bradley commented on packages/connectors/src/apps/dropbox/actions/upload-file/ui.tsx
> +          { id: "true", name: "True" },
Whoops I think my last comment was unclear. I'd like to use `true` and `false` as values, but "Yes" and "No" are better labels.

2024-04-24 21:33 UTC, blaise-bradley approved these changes

2024-04-25 15:41 UTC, merged