feat(discord): discord-integration
RolloutHQ/rollout pull request #9
Opened 2024-04-05 12:59 UTC by ChaitanyaVardhan

2024-04-10 16:46 UTC, blaise-bradley requested changes

2024-04-10 16:46 UTC, blaise-bradley commented on packages/connectors/src/apps/discord/README.md
> +
```suggestion
```

This should be clear from the `oauth.ts` file

2024-04-10 16:46 UTC, blaise-bradley commented on packages/connectors/src/apps/discord/lib/api.ts
> +export class DiscordAPI {
Our current pattern is to have a library of functions for interacting with the relevant api rather than a class.

See the `coda` connector for an example.

2024-04-10 16:46 UTC, blaise-bradley commented on packages/connectors/src/apps/discord/lib/api.ts
> +    const resource = `https://discord.com/api/guilds/${guildId}/channels`;
We should being use `assertFetchShape` here

2024-04-11 16:00 UTC, dodas commented on packages/connectors/src/env.ts
> +    DISCORD_BOT_TOKEN: z.string().optional()
let's remove this

2024-04-11 16:01 UTC, dodas commented on packages/connectors/src/env.ts
> +    DISCORD_BOT_TOKEN: z.string().optional()
or rather move it to `packages/connectors/src/apps/discord/env.ts`

2024-04-11 16:03 UTC, dodas commented on packages/connectors/src/apps/discord/queries.ts
> +    return channels.map((c: any) => ({ id: c.id, name: c.name }));
can we remove `:any` and instead add `assertFetchShape` in `getTextChannels()`

2024-04-11 16:04 UTC, dodas commented on packages/connectors/src/apps/discord/oauth.ts
> +  env: envSchema,
the content of `oauth.ts` file is now part of `auth.ts`, please merge `main` and check how `auth.ts` files look now.

2024-04-11 16:05 UTC, dodas commented on packages/connectors/src/apps/discord/oauth.ts
> +        guildId: token.guild.id,
let's make the bot token part of the credential, that way we can then read it from credential data in lib.
```suggestion
        guildId: token.guild.id,
        botToken: env.DISCORD_BOT_TOKEN,
```

2024-04-11 16:06 UTC, dodas commented on packages/connectors/src/apps/discord/lib/api.ts
> +export class DiscordAPI {
👍 yes please. going forward, let's have individual functions in separate files, rather than a single class.

2024-04-11 16:10 UTC, dodas commented on packages/connectors/src/apps/discord/oauth.ts
> +  env: envSchema,
and then add `supportedByRolloutCredentialsService: false`

2024-04-15 14:46 UTC, blaise-bradley requested changes

2024-04-15 14:46 UTC, blaise-bradley commented on packages/connectors/src/apps/discord/auth.ts
> +  supportedByRolloutCredentialsService: true,
```suggestion
  supportedByRolloutCredentialsService: true
```
 
The Rollout credentials service does not currently support Discord, it's whitelabel only

2024-04-15 14:46 UTC, blaise-bradley commented on packages/connectors/src/apps/discord/lib/change-guild-bot-name.ts
> +  const request = await fetch(resource, {
We want to use `assertFetchShape` for all requests. See `get-user` and `send-channel-message` as well.

2024-04-15 17:04 UTC, ChaitanyaVardhan commented on packages/connectors/src/apps/discord/auth.ts
> +  supportedByRolloutCredentialsService: true,
done. Testing locally with `false` is not possible.

2024-04-15 17:28 UTC, blaise-bradley approved these changes

2024-04-15 17:28 UTC, merged